name: flytime_spotify
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  carousel_slider: ^5.1.1
  custom_sliding_segmented_control: ^1.8.5
  flutter:
    sdk: flutter
  flutter_bounceable: ^1.2.0
  flutter_slider_drawer: ^3.0.2
  integration_test:
    sdk: flutter
  mockito: ^5.4.6
  mocktail: ^1.0.4
  provider: ^6.1.5
  test: ^1.25.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/google.png
    - assets/images/apple.png
    - assets/images/facebook.png
    - assets/images/billie.jpg
    - assets/images/ariana.jpg
    - assets/images/bts.jpg
    - assets/images/centralcee.jpg
    - assets/images/dualipa.jpg
    - assets/images/drake.jpg
    - assets/images/ed.jpg
    - assets/images/harry.jpg
    - assets/images/jorja.jpg
    - assets/images/lilwayne.jpg
    - assets/images/olivia.jpg
    - assets/images/rema.jpg
    - assets/images/rihanna.jpg
    - assets/images/uzi.jpg
    - assets/images/weekend.jpg
    - assets/images/travis.jpg
    - assets/images/doja.jpg
    - assets/images/tyga.jpg
    - assets/images/a1.jpeg
    - assets/images/a2.jpeg
    - assets/images/a3.jpeg
    - assets/images/a4.jpeg
    - assets/images/a5.jpeg
    - assets/images/b1.jpg
    - assets/images/b2.jpg
    - assets/images/b3.jpg
    - assets/images/b4.jpg
    - assets/images/c1.jpg
    - assets/images/c2.jpg
    - assets/images/d1.jpeg
    - assets/images/d2.jpeg
    - assets/images/p1.jpeg
    - assets/images/p2.jpeg
    - assets/images/cs1.jpeg
    - assets/images/cs2.jpeg
    - assets/images/c3.jpg
    - assets/images/c4.jpg
    - assets/images/ch1.jpeg
    - assets/images/ch2.jpeg
    - assets/images/ch3.jpeg
    - assets/images/ch4.jpeg
    - assets/images/n1.jpeg
    - assets/images/d3.jpeg
    - assets/images/u1.jpeg
    - assets/images/n2.jpeg
    - assets/images/u2.jpeg
    - assets/images/u3.jpeg
    - assets/images/g1.jpeg
    - assets/images/g2.jpeg
    - assets/images/o1.jpeg
    - assets/images/o2.jpeg
    - assets/images/n3.jpeg
    - assets/images/icon.png
    - assets/images/Icona.png
    - assets/images/T1.png
    - assets/images/T2.png
    - assets/images/m1.png
    - assets/images/m2.png
    - assets/images/playback.png
    - assets/images/rema1.jpeg
    - assets/images/rema2.jpeg
