name: flytime_spotify
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  carousel_slider: ^5.1.1
  flutter:
    sdk: flutter
  flutter_bounceable: ^1.2.0
  flutter_slider_drawer: ^3.0.2
  provider: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/google.png
    - assets/images/apple.png
    - assets/images/facebook.png
    - assets/images/billie.jpg
    - assets/images/ariana.jpg
    - assets/images/bts.jpg
    - assets/images/centralcee.jpg
    - assets/images/dualipa.jpg
    - assets/images/drake.jpg
    - assets/images/ed.jpg
    - assets/images/harry.jpg
    - assets/images/jorja.jpg
    - assets/images/lilwayne.jpg
    - assets/images/olivia.jpg
    - assets/images/rema.jpg
    - assets/images/rihanna.jpg
    - assets/images/uzi.jpg
    - assets/images/weekend.jpg
    - assets/images/travis.jpg
    - assets/images/doja.jpg
    - assets/images/tyga.jpg
    - assets/images/a1.jpeg
    - assets/images/a2.jpeg
    - assets/images/a3.jpeg
    - assets/images/a4.jpeg
    - assets/images/a5.jpeg
    - assets/images/b1.jpg
    - assets/images/b2.jpg
    - assets/images/b3.jpg
    - assets/images/b4.jpg
    - assets/images/c1.jpg
    - assets/images/c2.jpg
    - assets/images/c3.jpg
    - assets/images/c4.jpg
    - assets/images/icon.png
    - assets/images/rema1.jpeg
